# -*- coding: utf-8 -*-
"""falkordb_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtdWZVHwX4DJDd1YhQiHb83krv-Wy41C
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install falkordb langchain-falkordb langchain-core langchain-openai langchain-experimental

import os
from falkordb import FalkorDB
from langchain_openai import ChatOpenAI
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_core.documents import Document
from langchain_community.graphs import FalkorDBGraph
from google.colab import userdata

db = FalkorDB(
    host=userdata.get("FALKORDB_HOST"),
    port=userdata.get("FALKORDB_PORT"),
    username=userdata.get("FALKORDB_USERNAME"),
    password=userdata.get("FALKORDB_PASSWORD")
)

db.list_graphs()

"""## **Teste**"""

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_KEY")

TEXTO_FINETUNING = """
Fine-tuning é uma técnica de transfer learning que adapta um modelo pré-treinado
para uma tarefa específica. Modelos como BERT, GPT e LLaMA são frequentemente
usados como base para fine-tuning.

O processo de fine-tuning envolve várias etapas. Primeiro, você seleciona um
modelo base pré-treinado. Em seguida, prepara um dataset específico para sua
tarefa, que pode ser classificação de texto, geração de texto, ou question answering.

Existem diferentes abordagens de fine-tuning:

1. Full Fine-Tuning: Todos os parâmetros do modelo são atualizados durante o
treinamento. Isso requer mais recursos computacionais mas pode dar melhores resultados.

2. LoRA (Low-Rank Adaptation): Uma técnica eficiente que adiciona pequenas matrizes
treináveis às camadas do modelo, mantendo os pesos originais congelados. LoRA foi
desenvolvida pela Microsoft e reduz significativamente o uso de memória.

3. QLoRA: Combina LoRA com quantização em 4-bit, permitindo fine-tuning de modelos
grandes como LLaMA-65B em uma única GPU. Foi desenvolvida por pesquisadores da
Universidade de Washington.

Ferramentas populares para fine-tuning incluem Hugging Face Transformers, que
oferece a classe Trainer para facilitar o processo. O PEFT (Parameter-Efficient
Fine-Tuning) é uma biblioteca da Hugging Face que implementa LoRA e outras
técnicas eficientes.

Para datasets, plataformas como Hugging Face Hub oferecem milhares de datasets
prontos. O processo de preparação de dados geralmente envolve tokenização usando
tokenizers específicos de cada modelo.

Hiperparâmetros importantes no fine-tuning incluem learning rate (geralmente
entre 1e-5 e 5e-5), batch size, número de epochs, e warmup steps. O optimizer
mais comum é o AdamW.

Métricas de avaliação variam conforme a tarefa: accuracy e F1-score para
classificação, perplexity para modelos de linguagem, e BLEU ou ROUGE para
geração de texto.
"""

print("=" * 60)
print("KNOWLEDGE GRAPH COM LLMGraphTransformer + FalkorDB")
print("=" * 60)

print("\n[1/3] Configurando LLM...")
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

print("[2/3] Extraindo knowledge graph do texto...")
transformer = LLMGraphTransformer(
    llm=llm,
)

documents = [Document(page_content=TEXTO_FINETUNING)]

graph_documents = transformer.convert_to_graph_documents(documents)

print(f"\nExtraído do texto:")
for doc in graph_documents:
    print(f"  - {len(doc.nodes)} nós")
    print(f"  - {len(doc.relationships)} relações")

    print("\n--- NÓS EXTRAÍDOS ---")
    for node in doc.nodes:
        print(f"  [{node.type}] {node.id}")

    print("\n--- RELAÇÕES EXTRAÍDAS ---")
    for rel in doc.relationships:
        print(f"  {rel.source.id} --[{rel.type}]--> {rel.target.id}")

def add_graph_documents_to_falkordb(graph, graph_documents):
    """Insere GraphDocuments do LangChain no FalkorDB."""
    for doc in graph_documents:
        # Inserir nós
        for node in doc.nodes:
            node_id = node.id.replace("'", "\\'")
            query = f"MERGE (n:{node.type} {{id: '{node_id}'}})"
            graph.query(query)

        # Inserir relações
        for rel in doc.relationships:
            source_id = rel.source.id.replace("'", "\\'")
            target_id = rel.target.id.replace("'", "\\'")
            query = f"""
                MATCH (a {{id: '{source_id}'}}), (b {{id: '{target_id}'}})
                MERGE (a)-[r:{rel.type}]->(b)
            """
            graph.query(query)


add_graph_documents_to_falkordb(graph, graph_documents)

db = FalkorDB(
    host=userdata.get("FALKORDB_HOST"),
    port=userdata.get("FALKORDB_PORT"),
    username=userdata.get("FALKORDB_USERNAME"),
    password=userdata.get("FALKORDB_PASSWORD")
)

graph = db.select_graph("finetuning_kg_3")

print("\nGrafo inserido com sucesso!")

db = FalkorDB(
    host=userdata.get("FALKORDB_HOST"),
    port=userdata.get("FALKORDB_PORT"),
    username=userdata.get("FALKORDB_USERNAME"),
    password=userdata.get("FALKORDB_PASSWORD")
)

graph = db.select_graph("finetuning_kg")

resultado = graph.query("MATCH p=()-[:USED_FOR]-() RETURN p")

len(resultado.result_set)

for row in resultado.result_set:
    path = row[0]

    # Acessar nós do path
    nodes = path.nodes()
    edges = path.edges()

    print("Nós:", [n.properties for n in nodes])
    print("Relações:", [e.relation for e in edges])
    print("---")



