# -*- coding: utf-8 -*-
"""knowledge_graph_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EEU4Ri6rW3LDdBks1wvkevkpQRF6VLU

# 🧠 Knowledge Graph Extractor from PDF

Este notebook extrai um **grafo de conhecimento** (Knowledge Graph) de arquivos PDF usando:
- **LangChain** para orquestração
- **OpenAI GPT** para extração de entidades e relações
- **NetworkX** para manipulação do grafo
- **Matplotlib/PyVis** para visualização

---

## 1. 📦 Instalação das Dependências
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Instala todas as dependências necessárias
# !pip install langchain langchain-community langchain-openai langchain-text-splitters
# !pip install pypdf networkx matplotlib
# !pip install pydantic pyvis

"""## 2. 🔑 Configuração da API Key

Você precisa de uma chave da API da OpenAI. Obtenha em: https://platform.openai.com/api-keys
"""

import os
from google.colab import userdata

# Opção 1: Usar Secrets do Colab (recomendado)
# Vá em 🔑 no painel esquerdo > adicione OPENAI_API_KEY
try:
    os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_KEY')
    print("✅ API Key carregada dos Secrets do Colab")
except:
    pass

# Opção 2: Inserir manualmente (descomente e preencha)
# os.environ["OPENAI_API_KEY"] = "sk-..."

# Verifica se a key está configurada
if not os.environ.get("OPENAI_API_KEY"):
    print("⚠️ OPENAI_API_KEY não configurada!")
    print("   Use os Secrets do Colab ou defina manualmente acima.")
else:
    print("✅ API Key configurada com sucesso!")

"""## 3. 📚 Imports e Modelos de Dados"""

import json
from typing import List, Optional

# PDF Processing
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# LLM e Chains
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field

# Graph e Visualização
import networkx as nx
import matplotlib.pyplot as plt
from pyvis.network import Network
from IPython.display import HTML, display

# Upload de arquivos no Colab
from google.colab import files

print("✅ Imports realizados com sucesso!")

# Modelos de dados para o Knowledge Graph

class Entity(BaseModel):
    """Representa uma entidade no grafo de conhecimento."""
    name: str = Field(description="Nome da entidade")
    type: str = Field(description="Tipo da entidade (pessoa, organização, conceito, local, evento, tecnologia, etc.)")
    description: Optional[str] = Field(default=None, description="Descrição breve da entidade")


class Relationship(BaseModel):
    """Representa uma relação entre duas entidades."""
    source: str = Field(description="Entidade de origem")
    target: str = Field(description="Entidade de destino")
    relation: str = Field(description="Tipo de relação (ex: trabalha_em, é_parte_de, criou, fundou, etc.)")
    description: Optional[str] = Field(default=None, description="Descrição da relação")


class KnowledgeGraphChunk(BaseModel):
    """Representa as entidades e relações extraídas de um chunk de texto."""
    entities: List[Entity] = Field(description="Lista de entidades identificadas")
    relationships: List[Relationship] = Field(description="Lista de relações entre entidades")


print("✅ Modelos de dados definidos!")

"""## 4. 🛠️ Classe Principal: KnowledgeGraphExtractor"""

class KnowledgeGraphExtractor:
    """
    Classe principal para extração de Knowledge Graph de PDFs.

    Uso:
        extractor = KnowledgeGraphExtractor()
        extractor.extract_from_pdf("documento.pdf")
        extractor.visualize_interactive()
    """

    # Cores para cada tipo de entidade
    TYPE_COLORS = {
        "pessoa": "#FF6B6B",
        "organização": "#4ECDC4",
        "conceito": "#45B7D1",
        "local": "#96CEB4",
        "evento": "#FFEAA7",
        "tecnologia": "#DDA0DD",
        "produto": "#F0E68C",
        "data": "#87CEEB",
        "unknown": "#DFE6E9"
    }

    def __init__(self, model: str = "gpt-4o-mini", temperature: float = 0):
        """
        Inicializa o extrator.

        Args:
            model: Modelo OpenAI a usar (default: gpt-4o-mini)
            temperature: Temperatura para geração (default: 0 para determinismo)
        """
        self.llm = ChatOpenAI(
            model=model,
            temperature=temperature
        )

        self.parser = PydanticOutputParser(pydantic_object=KnowledgeGraphChunk)

        self.prompt = ChatPromptTemplate.from_messages([
            ("system", """Você é um especialista em extração de conhecimento estruturado.
Sua tarefa é extrair entidades e relações de textos para construir um grafo de conhecimento.

REGRAS IMPORTANTES:
1. Identifique TODAS as entidades importantes:
   - Pessoas (nome, cargo, papel)
   - Organizações (empresas, instituições, grupos)
   - Conceitos (ideias, teorias, métodos)
   - Locais (países, cidades, lugares)
   - Eventos (conferências, acontecimentos)
   - Tecnologias (ferramentas, linguagens, frameworks)
   - Produtos (softwares, serviços)
   - Datas (anos, períodos)

2. Para cada relação, use verbos claros como:
   - criou, fundou, desenvolveu
   - trabalha_em, pertence_a
   - é_parte_de, é_tipo_de
   - ocorreu_em, aconteceu_em
   - usa, utiliza, baseia_em

3. Mantenha nomes CONSISTENTES (mesma entidade = mesmo nome)
4. Extraia APENAS informações explícitas no texto
5. Seja ABRANGENTE - capture todas as conexões possíveis

{format_instructions}"""),
            ("human", "Extraia as entidades e relações do seguinte texto:\n\n{text}")
        ])

        self.chain = self.prompt | self.llm | self.parser

        # Grafo consolidado
        self.graph = nx.DiGraph()
        self.entities = {}  # name -> Entity
        self.relationships = []

        print(f"✅ Extrator inicializado com modelo: {model}")

    def load_pdf(self, pdf_path: str, chunk_size: int = 2000, chunk_overlap: int = 200) -> List[str]:
        """
        Carrega e processa um PDF em chunks de texto.

        Args:
            pdf_path: Caminho para o arquivo PDF
            chunk_size: Tamanho de cada chunk
            chunk_overlap: Sobreposição entre chunks

        Returns:
            Lista de chunks de texto
        """
        print(f"📄 Carregando PDF: {pdf_path}")
        loader = PyPDFLoader(pdf_path)
        documents = loader.load()

        print(f"   Páginas carregadas: {len(documents)}")

        # Divide em chunks menores para processamento
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            separators=["\n\n", "\n", ". ", " ", ""]
        )
        chunks = text_splitter.split_documents(documents)

        print(f"📝 PDF dividido em {len(chunks)} chunks")
        return [chunk.page_content for chunk in chunks]

    def extract_from_chunk(self, text: str) -> KnowledgeGraphChunk:
        """
        Extrai entidades e relações de um chunk de texto.

        Args:
            text: Texto para processar

        Returns:
            KnowledgeGraphChunk com entidades e relações
        """
        try:
            result = self.chain.invoke({
                "text": text,
                "format_instructions": self.parser.get_format_instructions()
            })
            return result
        except Exception as e:
            print(f"⚠️ Erro ao processar chunk: {e}")
            return KnowledgeGraphChunk(entities=[], relationships=[])

    def extract_from_text(self, text: str) -> KnowledgeGraphChunk:
        """
        Extrai entidades e relações de um texto direto.
        Útil para testes rápidos.

        Args:
            text: Texto para processar

        Returns:
            KnowledgeGraphChunk com entidades e relações
        """
        print("🔍 Extraindo conhecimento do texto...")
        chunk = self.extract_from_chunk(text)
        self._consolidate(chunk)
        print(f"✅ Extraído: {len(chunk.entities)} entidades, {len(chunk.relationships)} relações")
        return chunk

    def _consolidate(self, chunk: KnowledgeGraphChunk):
        """
        Consolida as entidades e relações de um chunk no grafo principal.

        Args:
            chunk: KnowledgeGraphChunk extraído
        """
        # Adiciona entidades
        for entity in chunk.entities:
            name = entity.name.strip().lower()
            if name not in self.entities:
                self.entities[name] = entity
                self.graph.add_node(
                    name,
                    type=entity.type.lower(),
                    description=entity.description or "",
                    label=entity.name  # Label original para exibição
                )

        # Adiciona relações
        for rel in chunk.relationships:
            source = rel.source.strip().lower()
            target = rel.target.strip().lower()

            # Garante que os nós existem
            if source not in self.graph:
                self.graph.add_node(source, type="unknown", description="", label=rel.source)
            if target not in self.graph:
                self.graph.add_node(target, type="unknown", description="", label=rel.target)

            # Adiciona aresta se não existir
            if not self.graph.has_edge(source, target):
                self.graph.add_edge(
                    source,
                    target,
                    relation=rel.relation,
                    description=rel.description or ""
                )
                self.relationships.append(rel)

    def extract_from_pdf(self, pdf_path: str, max_chunks: int = None, verbose: bool = True) -> nx.DiGraph:
        """
        Extrai o knowledge graph completo de um PDF.

        Args:
            pdf_path: Caminho para o PDF
            max_chunks: Número máximo de chunks a processar (None = todos)
            verbose: Se True, mostra progresso detalhado

        Returns:
            NetworkX DiGraph com o knowledge graph
        """
        chunks = self.load_pdf(pdf_path)

        if max_chunks:
            chunks = chunks[:max_chunks]
            print(f"⚠️ Limitado a {max_chunks} chunks")

        print(f"\n🔍 Extraindo conhecimento de {len(chunks)} chunks...\n")

        for i, chunk in enumerate(chunks, 1):
            if verbose:
                print(f"  [{i}/{len(chunks)}] Processando...", end=" ")

            kg_chunk = self.extract_from_chunk(chunk)
            self._consolidate(kg_chunk)

            if verbose:
                print(f"✓ (+{len(kg_chunk.entities)} entidades, +{len(kg_chunk.relationships)} relações)")

        print(f"\n" + "="*50)
        print(f"✅ EXTRAÇÃO CONCLUÍDA!")
        print(f"   Total de entidades: {self.graph.number_of_nodes()}")
        print(f"   Total de relações: {self.graph.number_of_edges()}")
        print(f"="*50)

        return self.graph

    def reset(self):
        """Limpa o grafo para começar uma nova extração."""
        self.graph = nx.DiGraph()
        self.entities = {}
        self.relationships = []
        print("🔄 Grafo resetado!")

    def get_summary(self) -> str:
        """Retorna um resumo do knowledge graph."""
        if self.graph.number_of_nodes() == 0:
            return "⚠️ Grafo vazio."

        # Conta tipos de entidades
        type_counts = {}
        for node in self.graph.nodes():
            node_type = self.graph.nodes[node].get("type", "unknown")
            type_counts[node_type] = type_counts.get(node_type, 0) + 1

        # Encontra entidades mais conectadas
        centrality = nx.degree_centrality(self.graph)
        top_entities = sorted(centrality.items(), key=lambda x: x[1], reverse=True)[:5]

        summary = [
            "\n" + "="*50,
            "📊 RESUMO DO KNOWLEDGE GRAPH",
            "="*50,
            f"\n📌 Total de Entidades: {self.graph.number_of_nodes()}",
            f"🔗 Total de Relações: {self.graph.number_of_edges()}",
            "\n📁 Entidades por Tipo:"
        ]

        for tipo, count in sorted(type_counts.items(), key=lambda x: x[1], reverse=True):
            emoji = {"pessoa": "👤", "organização": "🏢", "conceito": "💡",
                     "local": "📍", "evento": "📅", "tecnologia": "⚙️"}.get(tipo, "•")
            summary.append(f"   {emoji} {tipo.title()}: {count}")

        summary.append("\n⭐ Entidades Mais Conectadas:")
        for entity, score in top_entities:
            label = self.graph.nodes[entity].get("label", entity)
            summary.append(f"   • {label} (centralidade: {score:.3f})")

        return "\n".join(summary)

    def visualize_static(self, figsize: tuple = (16, 12), save_path: str = None):
        """
        Visualiza o knowledge graph como imagem estática.

        Args:
            figsize: Tamanho da figura
            save_path: Caminho para salvar (opcional)
        """
        if self.graph.number_of_nodes() == 0:
            print("⚠️ Grafo vazio, nada para visualizar.")
            return

        plt.figure(figsize=figsize)

        # Layout
        pos = nx.spring_layout(self.graph, k=2, iterations=50, seed=42)

        # Cores por tipo
        node_colors = [
            self.TYPE_COLORS.get(
                self.graph.nodes[node].get("type", "unknown"),
                self.TYPE_COLORS["unknown"]
            )
            for node in self.graph.nodes()
        ]

        # Desenha
        nx.draw_networkx_nodes(self.graph, pos, node_color=node_colors,
                               node_size=2000, alpha=0.9)
        nx.draw_networkx_edges(self.graph, pos, edge_color="#95A5A6",
                               arrows=True, arrowsize=20, alpha=0.7,
                               connectionstyle="arc3,rad=0.1")

        # Labels
        labels = {node: self.graph.nodes[node].get("label", node).title()
                  for node in self.graph.nodes()}
        nx.draw_networkx_labels(self.graph, pos, labels=labels,
                                font_size=8, font_weight="bold")

        edge_labels = nx.get_edge_attributes(self.graph, "relation")
        nx.draw_networkx_edge_labels(self.graph, pos, edge_labels=edge_labels,
                                     font_size=6, font_color="#7F8C8D")

        # Legenda
        legend_elements = [
            plt.scatter([], [], c=color, s=100, label=tipo.title())
            for tipo, color in self.TYPE_COLORS.items()
            if tipo != "unknown"
        ]
        plt.legend(handles=legend_elements, loc="upper left", title="Tipos")

        plt.title("🧠 Knowledge Graph", fontsize=16, fontweight="bold")
        plt.axis("off")
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor="white")
            print(f"💾 Imagem salva em: {save_path}")

        plt.show()

    def visualize_interactive(self, height: str = "600px", width: str = "100%"):
        """
        Cria uma visualização interativa do grafo usando PyVis.

        Args:
            height: Altura do widget
            width: Largura do widget
        """
        if self.graph.number_of_nodes() == 0:
            print("⚠️ Grafo vazio, nada para visualizar.")
            return

        # Cria rede PyVis
        net = Network(height=height, width=width, bgcolor="#ffffff",
                      font_color="#333333", notebook=True, cdn_resources='in_line')

        # Adiciona nós
        for node in self.graph.nodes():
            node_data = self.graph.nodes[node]
            node_type = node_data.get("type", "unknown")
            label = node_data.get("label", node)
            description = node_data.get("description", "")
            color = self.TYPE_COLORS.get(node_type, self.TYPE_COLORS["unknown"])

            title = f"<b>{label}</b><br>Tipo: {node_type}"
            if description:
                title += f"<br>{description}"

            net.add_node(node, label=label, title=title, color=color,
                         size=25 + self.graph.degree(node) * 5)

        # Adiciona arestas
        for source, target in self.graph.edges():
            edge_data = self.graph.edges[source, target]
            relation = edge_data.get("relation", "")
            net.add_edge(source, target, title=relation, label=relation,
                         arrows="to", color="#95A5A6")

        # Configurações de física
        net.set_options("""
        var options = {
          "physics": {
            "forceAtlas2Based": {
              "gravitationalConstant": -50,
              "centralGravity": 0.01,
              "springLength": 100,
              "springConstant": 0.08
            },
            "solver": "forceAtlas2Based"
          },
          "edges": {
            "smooth": {"type": "continuous"}
          }
        }
        """)

        # Salva e exibe
        net.save_graph("knowledge_graph.html")
        display(HTML(open("knowledge_graph.html").read()))
        print("\n💡 Dica: Arraste os nós para reorganizar o grafo!")

    def export_json(self, output_path: str = "knowledge_graph.json"):
        """
        Exporta o knowledge graph para JSON.

        Args:
            output_path: Caminho para salvar
        """
        data = {
            "entities": [
                {
                    "name": self.graph.nodes[name].get("label", name),
                    "type": self.graph.nodes[name].get("type", "unknown"),
                    "description": self.graph.nodes[name].get("description", "")
                }
                for name in self.graph.nodes()
            ],
            "relationships": [
                {
                    "source": self.graph.nodes[u].get("label", u),
                    "target": self.graph.nodes[v].get("label", v),
                    "relation": self.graph.edges[u, v].get("relation", ""),
                    "description": self.graph.edges[u, v].get("description", "")
                }
                for u, v in self.graph.edges()
            ],
            "statistics": {
                "total_entities": self.graph.number_of_nodes(),
                "total_relationships": self.graph.number_of_edges()
            }
        }

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"💾 JSON exportado para: {output_path}")
        return data


print("✅ Classe KnowledgeGraphExtractor definida!")

"""## 5. 🧪 Teste com Texto de Exemplo

Vamos testar o extrator com um texto de exemplo antes de processar um PDF.
"""

# Texto de exemplo para teste
SAMPLE_TEXT = """
A Inteligência Artificial (IA) é um campo da ciência da computação que foi
fundado em 1956 na Conferência de Dartmouth. John McCarthy, considerado o
pai da IA, cunhou o termo nessa conferência. Outros pioneiros importantes
incluem Alan Turing, que propôs o famoso Teste de Turing, e Marvin Minsky,
que co-fundou o Laboratório de IA do MIT.

O Machine Learning é uma subárea da IA que permite que sistemas aprendam
com dados. Deep Learning, por sua vez, é uma técnica de Machine Learning
baseada em redes neurais artificiais. Geoffrey Hinton, Yann LeCun e Yoshua
Bengio são considerados os "padrinhos do Deep Learning" e receberam o
Prêmio Turing em 2018 por seus trabalhos.

Empresas como Google, OpenAI e Anthropic estão na vanguarda da pesquisa em IA.
O Google desenvolveu o Transformer, arquitetura que revolucionou o processamento
de linguagem natural. A OpenAI criou o GPT e o ChatGPT, enquanto a Anthropic
desenvolveu o Claude.
"""

print("📝 Texto de exemplo carregado!")
print("-" * 50)
print(SAMPLE_TEXT[:300] + "...")

# Inicializa o extrator e processa o texto de exemplo
extractor = KnowledgeGraphExtractor(model="gpt-4o-mini")

# Extrai conhecimento
extractor.extract_from_text(SAMPLE_TEXT)

# Mostra resumo
print(extractor.get_summary())

# Visualização estática (matplotlib)
extractor.visualize_static(figsize=(14, 10))

# Visualização interativa (PyVis) - arraste os nós!
extractor.visualize_interactive(height="500px")

"""## 6. 📄 Extrair Knowledge Graph de um PDF

Agora vamos processar um arquivo PDF real.
"""

# Faz upload do PDF
print("📤 Faça upload do seu arquivo PDF:")
uploaded = files.upload()

# Pega o nome do arquivo
pdf_filename = list(uploaded.keys())[0]
print(f"\n✅ Arquivo carregado: {pdf_filename}")

# Cria novo extrator (limpo) e processa o PDF
pdf_extractor = KnowledgeGraphExtractor(model="gpt-4o-mini")

# Extrai o knowledge graph
# Use max_chunks para limitar o processamento em PDFs grandes
pdf_extractor.extract_from_pdf(
    pdf_filename,
    max_chunks=10,  # Remova ou aumente para processar mais
    verbose=True
)

# Mostra resumo
print(pdf_extractor.get_summary())

# Visualização estática
pdf_extractor.visualize_static(figsize=(16, 12), save_path="kg_pdf.png")

# Visualização interativa
pdf_extractor.visualize_interactive(height="600px")

"""## 7. 💾 Exportar Resultados"""

# Exporta para JSON
data = pdf_extractor.export_json("knowledge_graph.json")

# Mostra preview do JSON
print("\n📋 Preview do JSON:")
print(json.dumps(data, ensure_ascii=False, indent=2)[:1000] + "...")

# Download dos arquivos gerados
print("📥 Baixando arquivos...")

try:
    files.download("knowledge_graph.json")
    files.download("knowledge_graph.html")
    files.download("kg_pdf.png")
    print("✅ Downloads iniciados!")
except:
    print("⚠️ Alguns arquivos podem não existir ainda.")

"""## 8. 🔍 Análise Avançada do Grafo"""

# Análise de métricas do grafo
def analyze_graph(extractor):
    """Analisa métricas do knowledge graph."""
    G = extractor.graph

    if G.number_of_nodes() == 0:
        print("⚠️ Grafo vazio!")
        return

    print("\n" + "="*50)
    print("📊 ANÁLISE DO KNOWLEDGE GRAPH")
    print("="*50)

    # Métricas básicas
    print(f"\n📌 Métricas Básicas:")
    print(f"   • Nós: {G.number_of_nodes()}")
    print(f"   • Arestas: {G.number_of_edges()}")
    print(f"   • Densidade: {nx.density(G):.4f}")

    # Componentes
    if G.is_directed():
        n_components = nx.number_weakly_connected_components(G)
    else:
        n_components = nx.number_connected_components(G)
    print(f"   • Componentes conectados: {n_components}")

    # Centralidade
    print(f"\n⭐ Top 10 por Centralidade de Grau:")
    degree_cent = nx.degree_centrality(G)
    for node, cent in sorted(degree_cent.items(), key=lambda x: x[1], reverse=True)[:10]:
        label = G.nodes[node].get("label", node)
        print(f"   • {label}: {cent:.4f}")

    # PageRank
    print(f"\n🔥 Top 10 por PageRank:")
    pagerank = nx.pagerank(G)
    for node, pr in sorted(pagerank.items(), key=lambda x: x[1], reverse=True)[:10]:
        label = G.nodes[node].get("label", node)
        print(f"   • {label}: {pr:.4f}")

    # Relações mais frequentes
    print(f"\n🔗 Tipos de Relações mais Frequentes:")
    relations = [G.edges[e].get("relation", "") for e in G.edges()]
    relation_counts = {}
    for r in relations:
        relation_counts[r] = relation_counts.get(r, 0) + 1
    for rel, count in sorted(relation_counts.items(), key=lambda x: x[1], reverse=True)[:10]:
        print(f"   • {rel}: {count}")

# Executa análise
analyze_graph(pdf_extractor)

"""## 9. 🎯 Buscar Entidades e Relações Específicas"""

def search_entity(extractor, query: str):
    """Busca entidades que contenham o termo."""
    G = extractor.graph
    query = query.lower()

    results = []
    for node in G.nodes():
        if query in node:
            data = G.nodes[node]
            results.append({
                "name": data.get("label", node),
                "type": data.get("type", "unknown"),
                "description": data.get("description", ""),
                "connections": G.degree(node)
            })

    if results:
        print(f"\n🔍 Resultados para '{query}':")
        for r in results:
            print(f"   • {r['name']} ({r['type']}) - {r['connections']} conexões")
            if r['description']:
                print(f"     {r['description']}")
    else:
        print(f"\n⚠️ Nenhuma entidade encontrada para '{query}'")

    return results

def get_entity_relations(extractor, entity_name: str):
    """Mostra todas as relações de uma entidade."""
    G = extractor.graph
    entity = entity_name.lower()

    if entity not in G:
        # Tenta busca parcial
        matches = [n for n in G.nodes() if entity in n]
        if matches:
            entity = matches[0]
        else:
            print(f"⚠️ Entidade '{entity_name}' não encontrada")
            return

    label = G.nodes[entity].get("label", entity)
    print(f"\n🔗 Relações de '{label}':")

    # Relações de saída
    out_edges = list(G.out_edges(entity, data=True))
    if out_edges:
        print(f"\n   ➡️ Relações de saída:")
        for _, target, data in out_edges:
            target_label = G.nodes[target].get("label", target)
            print(f"      {label} --[{data.get('relation', '')}]--> {target_label}")

    # Relações de entrada
    in_edges = list(G.in_edges(entity, data=True))
    if in_edges:
        print(f"\n   ⬅️ Relações de entrada:")
        for source, _, data in in_edges:
            source_label = G.nodes[source].get("label", source)
            print(f"      {source_label} --[{data.get('relation', '')}]--> {label}")

# Exemplos de uso:
# search_entity(pdf_extractor, "google")
# get_entity_relations(pdf_extractor, "machine learning")

# Teste as funções de busca (modifique o termo de busca)
search_entity(extractor, "ia")

# Veja relações de uma entidade específica
get_entity_relations(extractor, "deep learning")

"""---

## 📚 Referências e Próximos Passos

### Bibliotecas Utilizadas:
- [LangChain](https://python.langchain.com/) - Framework para LLMs
- [NetworkX](https://networkx.org/) - Análise de grafos
- [PyVis](https://pyvis.readthedocs.io/) - Visualização interativa

### Melhorias Possíveis:
1. **Usar embeddings** para deduplicar entidades similares
2. **Adicionar RAG** para perguntas sobre o grafo
3. **Exportar para Neo4j** para análise avançada
4. **Fine-tuning** do prompt para domínios específicos
5. **Usar Claude/Gemini** como alternativa ao GPT

---

🎉 **Fim do notebook!**
"""